[package]
name = "yelp-fusion-rs-2"
version = "0.1.2"
edition = "2021"
rust-version = "1.65"
authors = ["Todd Everett Griffin <toddgriffin@protonmail.com>", "Ethan Cheatham"]
repository = "https://github.com/EVPitstop/yelp-fusion-rs"
homepage = "https://github.com/EVPitstop/yelp-fusion-rs"
description = "A Rust library for the Yelp Fusion API."
license = "MIT"
keywords = ["yelp", "fusion", "api", "http", "client"]
categories = ["web-programming", "api-bindings"]
exclude = [
    ".idea/*",
    ".github/*",
]

[dependencies]
# tokio
tokio = { version = "1", features = ["full"] }

# http request
reqwest = { version = "0.11", default-features = false, features = [ "json", "rustls-tls" ] }
bytes = "1.0"

# serde
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.81"
